### ISSUE TITLE
exclude vendor directory

### ISSUE THREAD

**Issue by Dexus** [360EntSecGroup-Skylar/goreporter#26]
see topic, it should be ignore the vendor dir.

**Comment by wgliang** [comment]
Yes, It did. But what is your error message? Can you post it?

**Comment by Dexus** [comment]
`github.com/go-siris/siris/vendor/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '=' (and 1 more errors)`

it's the error from the #25

**Comment by huyinghuan** [comment]
@wgliang   It do not exclude vendor directory.
![image](https://user-images.githubusercontent.com/3005433/28408264-7cb06f08-6d69-11e7-9f74-5d423b5880d4.png)
any option?

**Comment by wgliang** [comment]
Yes, please see #27
