### ISSUE TITLE
E0719 17:34:33.309647   97171 depend.go:81] failed to import 

### ISSUE THREAD

**Issue by yashpal1995** [360EntSecGroup-Skylar/goreporter#27]
E0719 17:34:33.309647   97171 depend.go:81] failed to import github.com/yashpal1995/mycode:
cannot find package "vendor/github.com/yashpal1995/mycode/" in any of:
$GOROOT
$GOPATH

$GOPATH/bin/goreporter -p github.com/yashpal1995/mycode -r ~/goreporter

why it's searching in vendor directory of $GOPATH?

**Comment by wgliang** [comment]
Because it is necessary to build a project dependent tree.If the default path is not found, check the vendor path.

**Comment by JulienTant** [comment]
I have the exact same issue. It looks like it cannot find my "local" packages :/

**Comment by wgliang** [comment]
@JulienTant What is the structure of your catalog?

**Comment by JulienTant** [comment]
it looks like 

```
root
  |- package1
	|- package1-1
	|- package1-2
  |- package2
	|- package2-1
	|- package2-2
	|- package2-3
  |- package3
	|- package3-1
	|- package3-1
```

where "root" is located in `$GOPATH/src/root`. 

So I `cd $GOPATH/src/root` and I run `goreporter -p . -r /tmp/report -f html`, then i got errors like 

```
can't load package "package1/package1-1": cannot find package "package1/package1-1" in any of:
        /usr/local/Cellar/go/1.8.3/libexec/src/package1/package1-1 (from $GOROOT)
        /Users/a/go/src/package1/package1-1 (from $GOPATH)
```

What is strange is that "root" is missing into the package name, I mean in code I import "root/package1/package1-1", never just "package1/package1-1"

I  hope my explainations are clear enough ^^

**Comment by wgliang** [comment]
I'm sorry,I got it. But I think you should run it like: goreporter -p ../root -r /tmp/report -f html.
You need to specify the relative path of your project and include the name root of your project.
This restriction is to avoid some ambiguity.
Hope to solve your problem.

**Comment by asheet-kumar** [comment]
@wgliang 
I am running following command from project directory to generate the report 
goreporter -p ../go_surge_app -e "vendor " -f html
But the problem is it includes packages in vendor directory and because of this average coverage % goes down. What is the way to exclude packages in vendor?

**Comment by wgliang** [comment]
I've added the vendor to the default exception keyword,due to a lot of feedback on the problem.
You can pull latest code and have a try. @asheet-kumar

**Comment by asheet-kumar** [comment]
Thanks @wgliang. it works now.

**Comment by JulienTant** [comment]
Thanks @wgliang

**Comment by wgliang** [comment]
At your call. @asheet-kumar @JulienTant
