### ISSUE TITLE
goreporter report error by run in terminal

### ISSUE THREAD

**Issue by xiaods** [360EntSecGroup-Skylar/goreporter#28]
<img width="1109" alt="2017-07-21 7 04 13" src="https://user-images.githubusercontent.com/37678/28442457-f056b588-6de2-11e7-8825-c7c7b6cb5061.png">

**Comment by wgliang** [comment]
Sorry, you must specify your project path. Just like :

**Comment by wgliang** [comment]
Sorry, you must specify your project path. Like
`goreporter -p [projectRelativePath] -r [reportPath] -e [exceptPackagesName] -f [json/html/text]  {-t templatePathIfHtml}`
