### ISSUE TITLE
function deepness

### ISSUE THREAD

**Issue by arthurgustin** [360EntSecGroup-Skylar/goreporter#33]
Hello, I've made a change in the gocyclo github.com/arthurgustin/gocyclo in order to get the max-depth of each function.
The problem is that:

    switch a {
        case 1:
        case 2:
        case 3:
        ...
        case N:
    }

which is ok to me, has a high cyclomatic complexity and is equivalent to

    if true {
        if true{
            if true {
                ...
                    if true {
                    }
            }
        }
    }
         
which is certainly not ok.

So I added an option in the CLI to do that.
Is there any way to integrate this change ? The user may choose what he wants, depending on the use case ?
I could work on it

**Comment by wgliang** [comment]
Thank you for your attention to goreporter. 
Goreporter as a tool, it is as easy as possible for users to use. And goreporter will output all the number complexity, does not need to be seted the maximum depth.
You can help me add more wonderful linters.
Thank you very much.

**Comment by arthurgustin** [comment]
Hi @wgliang, thank you for your fast answer.
So in your opition my feature request is much more like a new linter ?

**Comment by wgliang** [comment]
I mean this feature does not need to be added to gocyclo.

**Comment by arthurgustin** [comment]
Alright so may I propose a pull request with a new linter that will fit my use case ?

**Comment by wgliang** [comment]
Sorry, no need. 
I do not see the maximum depth than the gocyclo have more value.

**Comment by arthurgustin** [comment]
Well I tried to explain above, but in terms of code quality, I think it's important to detect whether a function needs to be splitted into several small functions, and the cyclomatic complexity may raise false positive, like a big switch case that sometimes cannot be avoided. Is our use case, the aim is to detect this kind of behavior before each code review in the continuous integration. 
Nevermind then, we will use this functionality outside of goreporter.

**Comment by wgliang** [comment]
I seem to understand what you mean, and you mean that the depth of the function is reduced as much as possible. When the depth of a function is greater than a certain value, it needs to be split into multiple functions. 

This is a great idea. We would love to add this linter to goreporter.

**Comment by arthurgustin** [comment]
Nice ! I already developed the tool github.com/arthurgustin/godepth
The code is close to gocyclo as it uses the same mechanics. I will propose a pull request asap
