### ISSUE TITLE
Some requirements

### ISSUE THREAD

**Issue by xkeyideal** [360EntSecGroup-Skylar/goreporter#43]
1. not just support vendor dir, should support absolutely dir
2. set the report default save dir
3. provide extensive documentation
4. whether support windows platform or not?

**Comment by wgliang** [comment]
1. The file under the vendor is imported outside, will be ignored default.
2. use -r [reportPath] will set  report save dir, current directory or not
3. you can just understand it by code, I will provide it some day maybe.
4. yes

Thanks.

**Comment by xkeyideal** [comment]
thx
