### ISSUE TITLE
expects import "mvdan.cc/lint"

### ISSUE THREAD

**Issue by gideonrid** [360EntSecGroup-Skylar/goreporter#45]
Can't get this library, because of:

```
MacBook-Pro-3:tmp gideon$ mkdir 2
MacBook-Pro-3:tmp gideon$ cd 2
MacBook-Pro-3:2 gideon$ ls
MacBook-Pro-3:2 gideon$ export GOPATH=`pwd`
MacBook-Pro-3:2 gideon$ go get -u github.com/360EntSecGroup-Skylar/goreporter
package github.com/mvdan/lint: code in directory /tmp/2/src/github.com/mvdan/lint expects import "mvdan.cc/lint"
```

**Comment by wgliang** [comment]
You should get it 
`go get github.com/mvdan/lint`

**Comment by wgliang** [comment]
I have been aware of the reasons why: github.com/mvdan/lint author modified the project's import path about 18 hours ago.

https://github.com/mvdan/lint/commit/f9de10a75144e429b05160cafa9637c79c1e453d

To prevent this from happening again, I would add the vendor directory to manage the outer package version.

Thanks.

**Comment by gideonrid** [comment]
Seems all good now, thanks

```
MacBook-Pro-3:tmp gideon$ mkdir 3
MacBook-Pro-3:tmp gideon$ cd 3
MacBook-Pro-3:3 gideon$ export GOPATH=`pwd`
MacBook-Pro-3:3 gideon$ go get -u github.com/360EntSecGroup-Skylar/goreporter
MacBook-Pro-3:3 gideon$ echo $?
0
```
