### ISSUE TITLE
Not finding all of my packages

### ISSUE THREAD

**Issue by mattstratton** [360EntSecGroup-Skylar/goreporter#46]
I have a project located in this path:

`$GOPATH/src/github.com/devopsdays/devopsdays-cli`

The file structure looks like this:

```
.
├── cmd
├── create
├── helpers
├── model
└── main.go
└── templates
    └── events
```
(that is to say, `cmd`, `create`, `helpers`, and `model` are all packages)

Inside of the `$GOPATH/src/github.com/devopsdays/devopsdays-cli` directory, I run:
`goreporter -p ../devopsdays-cli`

The dependency graph doesn't show anything:

![depgraph](https://i.imgur.com/RFYa7Sq.png)

However, if I go into the `helpers` directory and run:

`goreporter -p ../helpers`

I get the dep graph:

![helpers](https://i.imgur.com/jHpNVav.png)

Any ideas on what I might be doing wrong?

**Comment by wgliang** [comment]
I generated the report on my computer as follows:
goreporter -p ../devopsdays-cli
or
goreporter -p ../devopsdays-cli -f html



![wechatimg7](https://user-images.githubusercontent.com/8739301/31220402-efee0680-a985-11e7-9723-a2a62e9174c2.jpeg)

You can read the error message printed on the console.

**Comment by mattstratton** [comment]
I was sure I tried that in the various combinations of paths, but I guess I didn't, since it works! Thanks! I knew it was going to be something weird I was doing :)
