### ISSUE TITLE
Invalid javascript in generated html

### ISSUE THREAD

**Issue by ostronom** [360EntSecGroup-Skylar/goreporter#48]
The generated HTML document (with default template) is generated with an invalid javascript.

```
Uncaught SyntaxError: Unexpected token N in JSON at position 41
    at JSON.parse (<anonymous>)
    at Object.1../subpage/codeCount.js (dialog-platform-2017-11-09-17-55-01.html:879)
    at s (dialog-platform-2017-11-09-17-55-01.html:877)
    at e (dialog-platform-2017-11-09-17-55-01.html:877)
    at dialog-platform-2017-11-09-17-55-01.html:877
```

**Comment by wgliang** [comment]
Can you give wrong details, such as html files or screenshots? Then we will deal with it.

**Comment by ostronom** [comment]
Here is the final file.
[dialog-platform-2017-11-09-18-12-10.html.zip](https://github.com/360EntSecGroup-Skylar/goreporter/files/1458880/dialog-platform-2017-11-09-18-12-10.html.zip)

**Comment by bnkamalesh** [comment]
@wgliang I have the same issue too. For me, the error is at `resData.gotest = JSON.parse(resData.gotest)`. Probably when there are no tests?

**Comment by wgliang** [comment]
I've got it.This is because a divide by 0 operation causes NaN. 
Thx everyone!
