### ISSUE TITLE
seems wrong html format created

### ISSUE THREAD

**Issue by JiYou** [360EntSecGroup-Skylar/goreporter#49]
![image](https://user-images.githubusercontent.com/448253/33052202-54e88a8e-ce33-11e7-9a8d-99e2529d3530.png)

why this can happen?

**Comment by bnkamalesh** [comment]
It's some Javascript error.

**Comment by wgliang** [comment]
This is because a divide by 0 operation causes NaN. @JiYou 
You can pull the latest code to try again.
