### ISSUE TITLE
Items that lack the test file should have a warning or a low score prompt ?? 

### ISSUE THREAD

**Issue by KISSMonX** [360EntSecGroup-Skylar/goreporter#51]

**Comment by KISSMonX** [comment]
哦, 在北京, 应该是国人...
这个包很不错. 多谢分享. 
对于缺少测试文件的项目, 能否给个警告或者低分? 现在显示 0. 没有其他表示...

**Comment by wgliang** [comment]
Thanks for using. Unit testing is only one of the indicators, the score represents the overall quality of the project.

**Comment by KISSMonX** [comment]
OK, Thank you for your reply.
