### ISSUE TITLE
Unable to download godepth

### ISSUE THREAD

**Issue by aksh7860** [360EntSecGroup-Skylar/goreporter#52]
Getting 403 error

Initialized empty Git repository in /root/go/src/github.com/360EntSecGroup-Skylar/godepth/.git/
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/360EntSecGroup-Skylar/godepth/info/refs

**Comment by wgliang** [comment]
I do not understand you,and  no` github.com/360EntSecGroup-Skylar/godepth` project.

**Comment by aksh7860** [comment]
Actaully i needed to find the depth of functions used in go programs , so i was thinking of using godepth package.

But when i was downloading the godepth package i was given a 403 error.
So if could tell me any alternate way to find the depth of functions used in go programs

**Comment by wgliang** [comment]
You can get from https://github.com/arthurgustin/godepth

**Comment by aksh7860** [comment]
THanks for the help
