### ISSUE TITLE
Detect locks passed by value in goreporter

### ISSUE THREAD

**Issue by fearblackcat** [360EntSecGroup-Skylar/goreporter#61]
It’s not good and the root cause is Percentage method passes lock by value so engine.Summaries is actually called on a copy of the lock. It’s very easy to overlook, especially in bigger programs. It isn’t detected by the compiler since this might be an intention of the programmer. This is where vet steps in…
![qq20180503-105310](https://user-images.githubusercontent.com/5964503/39558439-2e7b85cc-4ec1-11e8-8998-5316be6819a6.png)
@wgliang 
So  I will pull request if you concur to fix this problem.

**Comment by wgliang** [comment]
Thank you so much for helping solve this problem.

**Comment by wgliang** [comment]
Come on!!!
